; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32 @6.5.0
board = esp32s3_flash_16MB
framework = arduino
monitor_speed = 115200 ;Serial Baud Rate Setting

; debug_tool = esp-builtin
; upload_protocol = esp-builtin
upload_speed = 921600 ; 460800, 512000, 460800, 256000, 115200
board_upload.flash_size = 16MB 

board_build.memory_type = qio_opi ;Enable internal PSRAM
; board_build.memory_type = qio_qspi ;Enable external PSRAM

board_build.partitions = default_16MB.csv 

build_flags = 
    -Wall ;all errors that everybody could agree on
    -Wextra ;somebody agree on
    ; -Werror ;Think of "Warning" as "Error".
    -D CORE_DEBUG_LEVEL=1 ;Debug level 0-5
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 ;1 is to use the USB port as a serial port
    -D ARDUINO_RUNNING_CORE=1       ; Arduino Runs On Core (setup, loop)
    -D ARDUINO_EVENT_RUNNING_CORE=1 ; Events Run On Core

lib_deps = 
    https://github.com/lathoub/Arduino-BLE-MIDI.git
    fortyseveneffects/MIDI Library@^5.0.2

[platformio]
boards_dir = ./boards
lib_dir = ./libraries

src_dir = tests
; default_envs = GFX
; default_envs = USB_Host_Camera_Screen
; default_envs = SY6970_OTG
; default_envs = RT9080
; default_envs = IIC_Scan_2
; default_envs = SD_Explorer_Music
; default_envs = Wifi_Music
; default_envs = Vibration_Motor
; default_envs = DMIC_ReadData
; default_envs = CST226SE
; default_envs = Deep_Sleep_Wake_Up
; default_envs = DMIC_SD
; default_envs = PCF85063
; default_envs = PCF85063_Timer_INT
; default_envs = PCF85063_Scheduled_INT
default_envs = Original_Test
; default_envs = Get_HTTP_Response_Time
; default_envs = WIFI_HTTP_Download_File
; default_envs = SY6970
; default_envs = WIFI_HTTP_Download_SD_file
; default_envs = SD_Music

; src_dir = debug/examples/${platformio.default_envs}
; default_envs = AW8624_RTP_EMR
; default_envs = AW8624_RAM_EMR
; default_envs = GFX_Camera_Screen_Proportion
; default_envs = SD_File_Size

[env:GFX]
[env:USB_Host_Camera_Screen]
[env:SY6970_OTG]
[env:RT9080]
[env:IIC_Scan_2]
[env:SD_Explorer_Music]
[env:Wifi_Music]
[env:Vibration_Motor]
[env:DMIC_ReadData]
[env:CST226SE]
[env:Deep_Sleep_Wake_Up]
[env:DMIC_SD]
[env:PCF85063]
[env:PCF85063_Timer_INT]
[env:PCF85063_Scheduled_INT]
[env:Original_Test]
[env:Get_HTTP_Response_Time]
[env:WIFI_HTTP_Download_File]
[env:SY6970]
[env:WIFI_HTTP_Download_SD_file]
[env:SD_Music]

[env:AW8624_RTP_EMR]
[env:AW8624_RAM_EMR]
[env:GFX_Camera_Screen_Proportion]
[env:SD_File_Size]

